onlyBuiltDependencies:
  - esbuild
overrides:
  postcss: 8.5.16
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  bufferutil: false
  esbuild: true
  sharp: false
  unrs-resolver: false
  utf-8-validate: false
